/* Câu 1 (1.5 điểm): Tạo cơ sở dữ liệu DANGKYHOC gồm 3 bảng.
SINHVIEN (MaSV, Ten,GioiTinh,NgaySinh,DiaChi)
MONHOC (MaMH, TenMH, NganhHoc)
DANGKY (MaSV, MaMH, NgayDK, HocKy) */
CREATE DATABASE DANGKYHOC
GO
USE DANGKYHOC
GO

CREATE TABLE SINHVIEN(
    MASV VARCHAR(20) PRIMARY KEY,
    TEN NVARCHAR(30),
    GIOITINH NVARCHAR(20),
    NGAYSINH DATE,
    DIACHI NVARCHAR(30)
)

CREATE TABLE MONHOC(
    MAMH VARCHAR(20) PRIMARY KEY,
    TENMH NVARCHAR(30),
    NGANHHOC NVARCHAR(30)
)

CREATE TABLE DANGKY(
    MASV VARCHAR(20),
    MAMH VARCHAR(20),
    NGAYDK DATE,
    HOCKY INT
)

ALTER TABLE DANGKY ADD FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)
ALTER TABLE DANGKY ADD FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
/* Câu 2 (3 điểm): Chèn thông tin vào các bảng
Tạo Stored Procedure (SP) với các tham số đầu vào phù hợp.
SP thứ nhất thực hiện chèn dữ liệu vào bảng SINHVIEN.
SP thứ hai thực hiện chèn dữ liệu vào bảng MONHOC.
SP thứ ba thực hiện chèn dữ liệu vào bảng DANGKY.
Yêu cầu mỗi SP phải kiểm tra tham số đầu vào. Với các cột không chấp nhận thuộc tính Null.
Với mỗi SP viết 3 lời gọi thành công. */
GO
CREATE PROC SP_SINHVIEN(
    @MASV VARCHAR(20),
    @TEN NVARCHAR(30),
    @GIOITINH NVARCHAR(20),
    @NGAYSINH DATE,
    @DIACHI NVARCHAR(30)
)
AS
IF @MASV IS NULL OR @TEN IS NULL OR @GIOITINH IS NULL OR @NGAYSINH IS NULL OR @DIACHI IS NULL
PRINT 'KHONG DUOC DE TRONG'
ELSE
INSERT INTO SINHVIEN VALUES(@MASV, @TEN, @GIOITINH, @NGAYSINH, @DIACHI)

EXEC SP_SINHVIEN @MASV = 'PH1', @TEN = 'NGUYEN VAN A', @GIOITINH = 'NAM', @NGAYSINH = '2001/01/01', @DIACHI = 'HA NOI'
EXEC SP_SINHVIEN @MASV = 'PH2', @TEN = 'NGUYEN VAN B', @GIOITINH = 'NAM', @NGAYSINH = '2001/02/03', @DIACHI = 'HAI PHONG'
EXEC SP_SINHVIEN @MASV = 'PH3', @TEN = 'NGUYEN THI C', @GIOITINH = 'NU', @NGAYSINH = '2001/04/08', @DIACHI = 'PHU THO'
SELECT * FROM SINHVIEN

GO
CREATE PROC SP_MONHOC(
    @MAMH VARCHAR(20),
    @TENMH NVARCHAR(30),
    @NGANHHOC NVARCHAR(30)
)
AS
IF @MAMH IS NULL OR @TENMH IS NULL OR @NGANHHOC IS NULL
PRINT 'KHONG DUOC DE TRONG'
ELSE
INSERT INTO MONHOC VALUES(@MAMH, @TENMH, @NGANHHOC)

EXEC SP_MONHOC @MAMH = 'COM2034', @TENMH = 'SQL', @NGANHHOC = 'PTPM'
EXEC SP_MONHOC @MAMH = 'MOB1014', @TENMH = 'JAVA1', @NGANHHOC = 'PTPM'
EXEC SP_MONHOC @MAMH = 'MOB1023', @TENMH = 'JAVA2', @NGANHHOC = 'PTPM'
SELECT * FROM MONHOC

GO
CREATE PROC SP_DANGKY(
    @MASV VARCHAR(20),
    @MAMH VARCHAR(20),
    @NGAYDK DATE,
    @HOCKY INT
)
AS
IF @MASV IS NULL OR @MAMH IS NULL OR @NGAYDK IS NULL OR @HOCKY IS NULL
PRINT 'KHONG DUOC DE TRONG'
ELSE
INSERT INTO DANGKY VALUES(@MASV, @MAMH, @NGAYDK, @HOCKY)

EXEC SP_DANGKY @MASV = 'PH1', @MAMH = 'COM2034', @NGAYDK = '2022/06/06', @HOCKY =3
EXEC SP_DANGKY @MASV = 'PH2', @MAMH = 'COM2034', @NGAYDK = '2022/06/06', @HOCKY =3
EXEC SP_DANGKY @MASV = 'PH3', @MAMH = 'MOB1023', @NGAYDK = '2022/06/06', @HOCKY =3
SELECT * FROM DANGKY
/* Câu 3 (2 điểm): Viết Hàm
Viết hàm các tham số đầu vào tương ứng với các cột của bảng SinhVien . Hàm này trả về MaSV thỏa mãn các giá trị được truyền tham số. */
GO
CREATE FUNCTION SEARCH(
    @MASV VARCHAR(20),
    @TEN NVARCHAR(30),
    @GIOITINH NVARCHAR(20),
    @NGAYSINH DATE,
    @DIACHI NVARCHAR(30)
)
RETURNS NVARCHAR(30)
BEGIN
    RETURN(SELECT MASV FROM SINHVIEN WHERE MASV = @MASV AND TEN = @TEN AND GIOITINH = @GIOITINH AND NGAYSINH = @NGAYSINH AND DIACHI = @DIACHI)
END

GO
DECLARE @MASV VARCHAR(20)
SET @MASV = dbo.SEARCH('PH1', 'NGUYEN VAN A', 'NAM', '2001/01/01', 'HA NOI')
SELECT @MASV AS 'MASV'

GO
CREATE FUNCTION SINHVIENSEARCH(@MASV VARCHAR(20))
RETURNS TABLE AS RETURN SELECT *
FROM SINHVIEN
WHERE MASV = @MASV
GO

SELECT *
FROM dbo.SINHVIENSEARCH('PH1')
/* Câu 4 (1.5 điểm): Tạo View 
Tạo View lưu thông tin của  ngày đăng ký gần nhất, gồm các thông tin sau: MaSV, TenSV,Tuổi, DiaChi, MaMH, TenMH, NgayDK, HocKy và sắp xếp giảm dần theo ngày đăng ký */
GO
CREATE VIEW SV
AS (SELECT TOP 1 SINHVIEN.MASV, SINHVIEN.TEN,(CAST(DATENAME(YEAR,GETDATE()) AS INT) -CAST(DATENAME(YEAR, NGAYSINH) AS INT)) [TUOI], SINHVIEN.DIACHI,
MONHOC.MAMH, MONHOC.TENMH, DANGKY.NGAYDK, DANGKY.HOCKY

FROM SINHVIEN JOIN DANGKY ON SINHVIEN.MASV = DANGKY.MASV JOIN MONHOC ON MONHOC.MAMH = DANGKY.MAMH 
ORDER BY NGAYDK DESC) -- ASC TANG DAN
GO
SELECT * FROM SV
/* Câu 5 (2 điểm): Viết thủ tục
Viết một SP nhận một tham số đầu vào là NgayDK. SP này thực hiện thao tác xóa thông tin sinh viên và môn học tương ứng.
Yêu cầu: Sử dụng giao dịch trong thân SP, để đảm bảo tính toàn vẹn dữ liệu khi một thao tác xóa thực hiện không thành công.
Lưu ý! Tên CSDL: CSDL_Tên Sinh Viên_MSSV. Xóa hết các CSDL trên máy. Ngắt internet, không trao đổi. Giám thị nhắc lần 1 trừ 2 điểm, lần 2 trừ 5 điểm, lần 3 hủy bài thi. */
GO
CREATE TRIGGER XOA_SV ON DANGKY AFTER DELETE
AS
BEGIN
    DELETE SINHVIEN WHERE MASV IN (SELECT MASV FROM DELETED)
    DELETE MONHOC WHERE MAMH IN (SELECT MAMH FROM DELETED)
END

GO
CREATE PROC XOA_SINHVIEN(@NGAYDK DATE)
AS
BEGIN
    DELETE DANGKY WHERE MASV IN (SELECT MASV FROM DANGKY WHERE NGAYDK = NGAYDK)
    DELETE DANGKY WHERE MAMH IN (SELECT MAMH FROM DANGKY WHERE NGAYDK = @NGAYDK)
END

SELECT * FROM SINHVIEN
SELECT * FROM MONHOC
SELECT * FROM DANGKY
EXEC XOA_SINHVIEN @NGAYDK = '2022/06/06'